### ISSUE TITLE
Front-end Design

### ISSUE THREAD

**Issue by AmarildoGrembi** [Build-Squad/asset-handover#16]
We will have to come up with a simple and user-friendly design.

**Comment by EndlessLucky** [comment]
Hi, this is the first comment as the front end developer of Asset Handover project.
I initialized the React project and pushed to the frontend branch. Once the design is ready, I'll implement the frontend according to it.
Meanwhile, I'll check the project structure and the readme so that I can have a deep understanding about the project.
